version: 3

vars:
  FOLDER: PE_PRN231_FA24_TrialTest_PhamDucThinh_Submit
  SOLUTION_NAME: PE_PRN231_FA24_TrialTest_PhamDucThinh
  BE_PRJ_NAME: PE_PRN231_FA24_TrialTest_PhamDucThinh_BE
  DB: ViroCureFAL2024DB

tasks:
  cook:
    desc: init prn prj
    dir: "{{.FOLDER}}"
    cmds:
      - dotnet new sln --name {{ .SOLUTION_NAME }}
      - dotnet new webapi --name {{ .BE_PRJ_NAME }} -f net8.0
      - dotnet new classlib --name BusinessObjects -f net8.0
      - dotnet new classlib --name DataAccess -f net8.0
      - dotnet new classlib --name Repositories -f net8.0
      - dotnet sln add ./{{.BE_PRJ_NAME}}/{{.BE_PRJ_NAME}}.csproj
      - dotnet sln add ./BusinessObjects/BusinessObjects.csproj
      - dotnet sln add ./DataAccess/DataAccess.csproj
      - dotnet sln add ./Repositories/Repositories.csproj
      - dotnet add ./{{.BE_PRJ_NAME}}/{{.BE_PRJ_NAME}}.csproj reference ./Repositories/Repositories.csproj
      - dotnet add ./Repositories/Repositories.csproj reference ./DataAccess/DataAccess.csproj
      - dotnet add ./DataAccess/DataAccess.csproj reference ./BusinessObjects/BusinessObjects.csproj
      - dotnet add ./DataAccess/DataAccess.csproj package Microsoft.EntityFrameworkCore.SqlServer --version 8.0.2 
      - dotnet add ./DataAccess/DataAccess.csproj package Microsoft.EntityFrameworkCore.Design --version 8.0.2 
      - dotnet add ./DataAccess/DataAccess.csproj package Microsoft.EntityFrameworkCore.Tools --version 8.0.2 
      - dotnet add ./DataAccess/DataAccess.csproj package Microsoft.Extensions.Configuration --version 8.0.0 
      - dotnet add ./DataAccess/DataAccess.csproj package Microsoft.Extensions.Configuration.Json --version 8.0.0
      - xcopy /A ..\\template\\DAO .\\DataAccess\\
      - xcopy /E ..\\template\\api .\\{{.BE_PRJ_NAME}}\\
      - xcopy /E ..\\template\\Repo .\\Repositories\\

  db:
    desc: scaffolding db
    dir: "{{.FOLDER}}/DataAccess"
    cmd: dotnet ef dbcontext scaffold "Server=(local); Database={{.DB}}; Uid=sa; Pwd=12345;TrustServerCertificate=True" Microsoft.EntityFrameworkCore.SqlServer --output-dir ../BusinessObjects --context-dir .